### ISSUE TITLE
Missing useful warning : identical names for multiple assets

### ISSUE THREAD

**Issue by Krobill** [ToolkitForDart/darttoolkit-extension#11]
When a bitmap image and a MovieClip have the same name in the Flash library, the MovieClip is automatically renamed [name]_1. The original name is used to create a Bitmap object in the dartLib. That's ok but making a clear warning in the output log that this is happening (and that it's definitely not recommended) would be nice and would save a lot of debug time in some cases.

**Comment by elsassph** [comment]
Toolkit for Dart 0.6 was released including this enhancement.
