### ISSUE TITLE
"LayerObj.jsfl": TypeError: frameXML has no properties

### ISSUE THREAD

**Issue by Javier-Esteban** [ToolkitForDart/darttoolkit-extension#16]
Hi,
I've done a simple flash movie, just some Tiles moving with classic interpolation.
When I try to export it to Dart, with the toolkit, I get the following error:

Se han producido los siguientes errores de JavaScript:
En la línea 280 del archivo "LayerObj.jsfl":
TypeError: frameXML has no properties

Am doing something wrong?

thanks in advance

**Comment by Javier-Esteban** [comment]
Hi, 
After hours of trying to find the problem, just minutes after posting the issue a got the exact bug.....
If I group the layers in folders I got the error, If I let the layers alone and delete de folders everything Works.

Thanks

**Comment by elsassph** [comment]
Thanks for reporting. This part comes from an old version of CreateJS Toolkit so it may be a bug inherited.

Do the layers have the same number of frames?

**Comment by Javier-Esteban** [comment]
Hi,
Yes they have, but I don't thinks thats the problem. 
With only one layer,, if I put that layer inside a folder, and make a simple animation the same error pops, But if I put the layer outside the folder, and delete the folder there is no error.

I've got another error with the constructor of stage in Dart, when created with the toolkit it has an extra attribute "framerate". I've solved it by deleting this param from the constructor call.

Best regards

**Comment by bp74** [comment]
Regarding the "framerate" issue - there were some breaking changes in StageXL 0.12 and i don't think that the Toolkit creates code that matches those breaking changes. The "framerate" parameter is no longer available on the Stage constructor, it moved to a static field called "MovieClip.defaultFrameRate" since MovieClip is the only class which used this setting.

More about the breaking changes can be found here:
https://groups.google.com/forum/#!topic/stagexl/TxvIss-m0GE

**Comment by Javier-Esteban** [comment]
Ok, thanks

Then... Toolkit_for_Dart_for_Adobe_Flash_Professional-0.5.2 for which versión of StageXL is fully compatible?

**Comment by bp74** [comment]
It should work fine with StageXL 0.11.0. 
You can update your pubspec.yaml file to use this specific version like this:

    dependencies:
      stagexl: ^0.11.0

**Comment by elsassph** [comment]
You should raise another issue for the framerate change, let's keep the discussion focused on layers.

**Comment by elsassph** [comment]
Note: I raised another issue for 0.12 compatibility update.

**Comment by elsassph** [comment]
Toolkit for Dart 0.6 has been released, solving this issue.
