### ISSUE TITLE
Small problems with TextField exports (TextInst.jsfl)

### ISSUE THREAD

**Issue by Krobill** [ToolkitForDart/darttoolkit-extension#5]
in TextInst.jsfl when the xml describing the TextField is converted to String, the  lineType attribute is not assigned correctly if the value should be 'single'. It works correctly with 'multiline' and 'multiline no wrap' though.

I made a dirty quick fix for me to replace everything which is not 'multiline' or 'multiline no wrap' by 'single' but the problem comes from earlier when the xml describing the TextField is generated : when the value should be single the attribute is just missing. Didn't have the courage to dig further for now but i'll check that later.

One small other thing : IMHO, the autoSize property should be set according to the textAlign value. Right now, it's either nothing or 'left', but it should be 'center' if the texte is centered or 'right' if the text is aligned to the right.

**Comment by elsassph** [comment]
Toolkit for Dart 0.6 was released including this fix.
