### ISSUE TITLE
Layer Folder Export issue

### ISSUE THREAD

**Issue by Krobill** [ToolkitForDart/darttoolkit-extension#7]
Hu sorry, in fact it's not sometimes it's every time that layer folders cause an exception when exporting. I was lost due to the fact that we used the darttoolkit version of the official site for a few days on a production computer while I was doing some testing with the github version on another.

So basically : one of the update between the official download version of the toolkit and this version broke the layer folder export.

**Comment by elsassph** [comment]
Duplicate of #16 - will be fixed in the next release
